export enum IconNameEnum {
  Home = 'home',
  Play = 'play',
  PlayList = 'playlist',
  Shuffle = 'shuffle',
  Pause = 'pause',
  PauseBack = 'pause-back',
  Volume = 'volume',
  Dot = 'dot',
  ArrowLeft = 'arrow-left',
  ArrowRight = 'arrow-right',
  Lock = 'lock',
  Plus = 'plus',
  Search = 'search',
  Album = 'album',
  Sun = 'sun',
  Moon = 'astronomy-moon',
  Logout = 'logout',
}
