export enum IconNameEnum {
  Home = 'home',
  Play = 'play-dark',
  PlayLight = 'play-light',
  PlayDark = 'play-dark',
  PlayList = 'playlist',
  Shuffle = 'shuffle',
  Pause = 'pause',
  PauseLight = 'pause-light',
  Volume = 'volume',
  Dot = 'dot',
  DotDark = 'dot-dark',
  ArrowLeft = 'arrow-left',
  ArrowRight = 'arrow-right',
  Lock = 'lock',
  Plus = 'plus',
  Search = 'search',
  Album = 'album',
  BackwardDesktop = 'backward-desktop',
  BackwardLight = 'backward-light',
  BackwardDark = 'backward-dark',
  ForwardDesktop = 'forward-desktop',
  ForwardLight = 'forward-light',
  ForwardDark = 'forward-dark',
  pauseIcon = "pauseIcon",
  playIcon = "playIcon"
}
