export enum IconNameEnum {
  Home = 'home',
  Play = 'play',
  PlayList = 'playlist',
  Shuffle = 'shuffle',
  Pause = 'pause',
  Volume = 'volume',
  Dot = 'dot',
  ArrowLeft = 'arrow-left',
  ArrowRight = 'arrow-right',
  Search = 'search',
  Album = 'album',
  Backward = 'backward',
  Forward = 'forward',
}
